services:
  github-runner:
    image: myoung34/github-runner:latest
    container_name: github-runner-${RUNNER_SCOPE}-${RUNNER_LABELS}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # 仅在需要覆盖.env文件中的值时才在这里指定
      RUNNER_NAME: "docker-runner-${RUNNER_LABELS}"  # 组织级别runner名称格式
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./runner-data:/data
    
    mem_limit: "2g"
    cpus: "1.0"